name: CI-template

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Pre-test script
        run: |
          if [[ -f "tests/pre_test.sh" ]]; then
            bash tests/pre_test.sh; fi
      - name: Install latest stable 3.x langinfra version
        run: |
          pip install langinfra
      - name: Python requirements
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt ; fi
          if [ -f tests/requirements.txt ]; then
            pip install -r tests/requirements.txt ; fi
